# Generated by Django 3.2.4 on 2021-12-08 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='adaptiv',
            field=models.BooleanField(null=True, verbose_name='да'),
        ),
    ]
