# Generated by Django 3.2.4 on 2021-12-04 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, upload_to='blog/images/', verbose_name='Фото'),
        ),
        migrations.AddField(
            model_name='blog',
            name='url',
            field=models.URLField(blank=True, verbose_name='Ссылка на пост'),
        ),
    ]
